### ISSUE TITLE
Hi， how to load the data

### ISSUE THREAD

**Issue by chengyu89527** [XRad-Ulm/Proto-Caps#1]
I check the dataset website. they provide dicom files(128G). How ever I see your dataset loader script trying to load npy pr h5 file. How can i get these files?

**Comment by LuisaGallee** [comment]
Hi,
when running the first time, these files are generated automatically in data_loader.py. 
This uses the package [pylidc](https://pylidc.github.io/install.html) to handle the data processing from the raw dicom files. Please follow the [installation procedure](https://pylidc.github.io/install.html), which includes downloading the [LIDC dataset](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=1966254) and then configuring pylidc by setting the path parameter to the downloaded folder.
If you have any further questions, please don't hesitate to contact me at luisa.gallee@uni-ulm.de .

**Comment by chengyu89527** [comment]
Thanks very much
&nbsp;


成大宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月27日(星期一) 晚上10:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XRad-Ulm/Proto-Caps] Hi， how to load the data (Issue #1)





 
Hi,
 when running the first time, these files are generated automatically in data_loader.py.
 This uses the package pylidc to handle the data processing from the raw dicom files. Please follow the installation procedure, which includes downloading the LIDC dataset and then configuring pylidc by setting the path parameter to the downloaded folder.
 If you have any further questions, please don't hesitate to contact me at ***@***.*** .
